### ISSUE TITLE
.editorconfig rather than IDEs formatters

### ISSUE THREAD

**Issue by f4bien** [Talend/data-prep#188]
Would it be better to put an [.editorconfig file](http://editorconfig.org/) at root path rather than include specific IDE formatters files?

**Comment by pbabin** [comment]
+1

**Comment by fhuaulme** [comment]
Yes, why not. Intellij supports it, I can't tell for Eclipse though. The idea behind using the Eclipse formatter configuration was to allow us to pick up Talend's code format.

**Comment by f4bien** [comment]
Eclipse needs a specific plugin https://marketplace.eclipse.org/content/editorconfig-eclipse

**Comment by fhuaulme** [comment]
Can you make a PR with an initial config file? (it may be only for JS code in a first step)

**Comment by sgandon** [comment]
looking at the site detailed supported properties if very poor and the few they have is not even supported by all plugins. I am not sure this will be of any use.

**Comment by jsomsanith** [comment]
I merged your PR.
But we have to share a common IDE config too. This is a good start when a developper use a new IDE.
