### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by arcuri82** [Talend/data-prep#444]
Hi,
  I was trying to compile this project for research reasons, but it fails :(

[INFO] Reactor Summary:
[INFO] 
[INFO] dataprep-backend ................................... SUCCESS [  0.485 s]
[INFO] dataprep-backend-common ............................ SUCCESS [  0.451 s]
[INFO] dataprep-actions ................................... SUCCESS [  0.060 s]
[INFO] dataprep-backend-service ........................... FAILURE [  2.796 s]

[ERROR] Failed to execute goal on project dataprep-backend-service: Could not resolve dependencies for project org.talend.dataprep:dataprep-backend-service:jar:2.1.0-SNAPSHOT: Failed to collect dependencies at org.talend.datastewardship:tql:jar:6.3.1: Failed to read artifact descriptor for org.talend.datastewardship:tql:jar:6.3.1: Could not transfer artifact org.talend.datastewardship:tql:pom:6.3.1 from/to releases (http://newbuild.talend.com:8081/nexus/content/repositories/releases): Not authorized , ReasonPhrase:Unauthorized. -> [Help 1]

**Comment by fhuaulme** [comment]
Hi,

Thanks for the feedback. This artifact should be in Talend's open source repository but isn't. This should also be fixed soon. 

Wéll update this issue as soon as it's available.

**Comment by fhuaulme** [comment]
This was just done as part of https://jira.talendforge.org/browse/TDP-4339. Thank you for your patience and many apologies for the really slow action on this!
